### ISSUE TITLE
Python3 executable not found in %PATH%

### ISSUE THREAD

**Issue by tusharhero** [jstrieb/quickserv#4]
![image](https://user-images.githubusercontent.com/54012021/147765191-9cdbf8d9-3e06-4315-a847-fa08d412563b.png)
i am running windows 10

**Comment by tusharhero** [comment]
I had to wsl to do it.

**Comment by jstrieb** [comment]
Hello @tusharhero! I think this is probably a local configuration issue, and not an issue with my repo code specifically.

For that reason, and because it seems like you solved it by using WSL (which I love!), I'll close this issue. Feel free to reopen it if you feel the issue was closed in error.
